### ISSUE TITLE
Let faculty assign Graders in addition to GEs

### ISSUE THREAD

**Issue by jechols** [uoregon-libraries/student-course-integrator#33]
We need to provide faculty a way to add a grader to a course.  There will need to be a dropdown or radio button to select the role of the student being added.

Anybody who's a student can be a grader, but it requires an extra UI element: the faculty member must agree that a student has signed a form and that form is on file.  We'll obviously need verbiage for all this, but we can build the core functionality and add the right text later.  Note that the verbiage will likely include a link to the form itself, so we need to make sure that if the text is configurable, it is rendered raw, otherwise the angle-brackets will be escaped.

Subtasks needed are listed below.  I'll check these off as tickets are made for them rather than as the work is completed.  Once all tickets are generated, this issue can be closed.

- [x] The form template will need the role dropdown / radio button (#36)
- [x] The form object will need to read and store the role (#36)
- [x] Valid roles might need to be put somewhere global, as well as a "is some string a valid role" function.  We could create a very simple "roles" package.  That feels like overkill for such a simple bit of data, but I like `role.Valid("foo")` and `role.All` far more than `global.ValidRole("foo")` and `global.AllRoles`. (#45)
- [x] The form object should validate that the role is in the approved list, which will be "GE" or "Grader" now. (#42)
- [x] The confirmation form needs the "I agree this student blah blah" checkbox if the role was Grader (#44)
- [x] The form object will need to read the "I agree this student blah blah" checkbox value (#44)
- [x] The form object will need to verify that the checkbox was used if the role was Grader.  Failure to check the box can be an error like any other. (#44)
- [x] Instead of `person.CanBeGE`, we probably want a more general check, like `person.CanBeRole(role)`.  `CanBeRole(role.Grader)` will always return true, but it will give us a place to add logic if we find we need to restrict graders in the future. (#49)
- [x] The form object will call the CanBeRole(role) and add an appropriate error message if the person in question cannot be the requested role. (#49)
- [x] Submission code paths need to check the role:
  - [x] The audit logging needs to send the role to the `audit.Log` calls (#37 overhauls auditing and is a blocker for this piece).
  - [x] The enrollment model will need a method that takes a role.  Right now, we just have `enrollment.AddGE`. (#59)
- [x] The enrollment model should validate the role, not just assume the form did, in case we use enrollments separately for some reason later on. (#59)
  - [x] #31 will make this easier, so should be tackled before this issue
- [x] Various messaging needs to be fixed where we hard-code "GE" in templates, info/alert messages, etc.
- [x] There may be other bits that need work

**Comment by jechols** [comment]
I think all tickets are now generated
